# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171103_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
