# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171103_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='analogues',
            field=models.ManyToManyField(related_name='_medication_analogues_+', to='main.Medication'),
        ),
    ]
