# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_medication_analogues'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='warn_kidney',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='warn_liver',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='warn_pregnancy',
            field=models.IntegerField(null=True),
        ),
    ]
